name: AutoMall - CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - dev


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo start ...
      - name: Jenkins execute
        run: curl http://106.12.34.36:8389/job/mall/build?token=TOKEN_AUTOMALL
